source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.0"

# Core
gem "rails", "~> 7.1.6"
gem 'pg', '~> 1.5'
gem 'puma', '~> 6.0'

# Authentication & Security
gem 'bcrypt', '~> 3.1.7'
gem 'jwt'
gem 'rack-cors'

# Payment processing
gem 'stripe'

# Background jobs
gem 'sidekiq', '~> 7.0'
gem 'sidekiq-cron', '~> 1.12'
# Alternative: gem 'whenever', require: false

# Environment variables
gem 'dotenv-rails', groups: [:development, :test]

# Pagination
gem 'kaminari', '~> 1.2'

# Serialization
gem 'active_model_serializers', '~> 0.10.0'

# Performance
gem 'bootsnap', require: false

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 6.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'database_cleaner-active_record'
end

group :development do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'shoulda-matchers', '~> 5.0'
  gem 'simplecov', require: false
end